registries:
  my-private-npm:
    type: "npm-registry"
    url: "https://npm.mycorp.com"
    token: "${{ secrets.NPM_TOKEN }}"
    
version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
